debug = false
checkNewVersion = false
logLevel = "INFO"

defaultEntryPoints = ["http", "https"]

[ping]
# entryPoint = "http"
entryPoint = "ping"

[api]
entryPoint = "api"
dashboard = true

[entryPoints]
  [entryPoints.http]
  address = ":80"

  [entryPoints.ping]
  address = ":8081"

  [entryPoints.api]
  address = ":8080"
    [entryPoints.http.redirect]
    entryPoint = "https"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    minVersion = "VersionTLS12"
    cipherSuites = [
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
      "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
      "TLS_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_RSA_WITH_AES_128_CBC_SHA",
      "TLS_RSA_WITH_AES_256_CBC_SHA"
    ]
    [[entryPoints.https.tls.certificates]]
    CertFile = "/certs/cert.crt"
    KeyFile = "/certs/cert.key"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "local.de"
watch = true
exposedbydefault = false
swarmmode = false

[accessLog]

# [metrics]
#   [metrics.prometheus]
#     entryPoint = "traefik"
#     buckets = [0.1,0.3,1.2,5.0]